DROP DATABASE IF EXISTS sis181;
CREATE DATABASE sis181;
USE sis181;

CREATE TABLE colleges (
    collegeCode VARCHAR(255) NOT NULL,
    collegeName VARCHAR(255) NOT NULL,
    PRIMARY KEY (collegeCode)
);
